export const ALL_COLUMNS = [
  { id: 'type', label: '구분', category: '기본정보' },
  { id: 'sequence', label: '순번', category: '기본정보' },
  { id: 'name', label: '상호명', category: '기본정보' },
  { id: 'abbreviation', label: '약칭', category: '기본정보' },
  { id: 'barcode', label: '바코드', category: '기본정보' },
  { id: 'ceo', label: '대표자', category: '기본정보' },
  { id: 'businessNo', label: '사업자번호', category: '기본정보' },
  { id: 'address', label: '주소', category: '기본정보' },
  { id: 'phone', label: '일반전화', category: '연락처' },
  { id: 'mobile', label: '휴대전화', category: '연락처' },
  { id: 'fax', label: '팩스', category: '연락처' },
  { id: 'email', label: '이메일', category: '연락처' },
  { id: 'manager', label: '담당자', category: '관리설정' },
  { id: 'warehouse', label: '담당창고', category: '관리설정' },
  { id: 'bankAccount', label: '은행/계좌', category: '관리설정' },
  { id: 'creditLimit', label: '여신한도', category: '관리설정' },
  { id: 'receivables', label: '누적 미수금', category: '관리설정' },
  { id: 'receivableBase', label: '기초미수', category: '관리설정' },
  { id: 'grade', label: '등급', category: '관리설정' },
  { id: 'loginId', label: '아이디', category: '로그인' },
  { id: 'password', label: '비밀번호', category: '로그인' },
  { id: 'hideOrderInfo', label: '주문정보숨김', category: '로그인' },
  { id: 'memo', label: '메모', category: '기본정보' }
];
